apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2yc0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2yc0
    app.kubernetes.io/part-of: tkrw-pr714-0075-0040-app
  name: devfile-sample-2yc0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2yc0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2yc0
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0040-tenant/tkrw-pr714-0075-0040-app/devfile-sample-2yc0@sha256:486716cf8bb5d0c3bcc0b470db3f95126b61e6ebef8ac7eaeecab3485278199d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
